version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./db_data:/app/db_data
    networks:
      - loharanobox-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - loharanobox-net

  docker-proxy:
    image: alpine/socat
    container_name: docker-proxy
    restart: unless-stopped
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - loharanobox-net

networks:
  loharanobox-net:
    driver: bridge
